# Enhanced ADCS Analysis Figures Explanation

This document explains the four figures generated by `all_simulate_enhanced.m`. These figures extend the original 3D satellite attitude animation into a quantitative ADCS and mission-availability analysis workflow.

The enhanced analysis focuses on four questions:

- Is the quaternion telemetry reliable enough for attitude reconstruction?
- Is the satellite attitude stable, or is it rotating/slewing?
- How well is the satellite pointing toward Earth, the Sun, and the Zhongli ground station?
- Is the satellite only geometrically visible, or is it also properly aligned for sensor or communication access?

## Figure 1: ADCS Quaternion Quality Check

![ADCS quaternion quality check](outputs_enhanced/figures/01_quaternion_quality.png)

### Purpose

This figure checks whether the ADCS quaternion telemetry is reliable. Since quaternion data is the basis for attitude reconstruction, it must be validated before using it for pointing-error or access analysis.

### What the Figure Shows

The upper plot shows:

```text
Quaternion norm before normalization
```

For a valid unit quaternion, the norm should be close to `1`. In this dataset, the raw quaternion norm is approximately `0.992` and remains stable over time. This indicates that the telemetry does not contain obvious invalid values, NaNs, or large discontinuities.

The lower plot shows the normalized quaternion components:

```text
qx, qy, qz, qw
```

These components describe how the satellite attitude changes over time. Several clear transitions can be observed, indicating that the satellite attitude is not fixed and may include attitude maneuvers or control actions.

### Engineering Meaning

This figure confirms that the quaternion telemetry is consistent enough to support attitude reconstruction. Although the raw norm is not exactly `1`, the error is small and stable, and the quaternion can be normalized before further analysis.

## Figure 2: ADCS Body-Rate Stability

![ADCS body-rate stability](outputs_enhanced/figures/02_body_rate_stability.png)

### Purpose

This figure evaluates the satellite angular rate, which is used to determine whether the spacecraft attitude is stable or undergoing rotation, slewing, or disturbance.

### What the Figure Shows

The upper plot shows the three-axis body rates:

```text
Estimated body rates in ORC frame
```

The body rates are shown for the X, Y, and Z axes in `deg/s`.

The lower plot shows:

```text
Total angular rate
```

This is the combined magnitude of the three-axis angular rate. The dashed red line represents the stability threshold:

```text
0.08 deg/s
```

### Results

The main computed results are:

```text
Body-rate RMS = 0.3524 deg/s
Stable-rate fraction = 97.60%
Maximum body rate = 4.81 deg/s
```

Most of the dataset has very low angular rate, with only two clear spikes.

### Engineering Meaning

The satellite appears to be attitude-stable for most of the analyzed period. The two angular-rate spikes may correspond to attitude-control actions, slew maneuvers, transient disturbances, or short estimator changes.

## Figure 3: Telemetry-Derived Pointing Performance

![Telemetry-derived pointing performance](outputs_enhanced/figures/03_pointing_errors.png)

### Purpose

This figure converts quaternion telemetry into engineering-level pointing metrics. Instead of only visualizing attitude in 3D, it evaluates how well the satellite points toward key mission directions.

### What the Figure Shows

The first plot shows:

```text
Nadir / Earth-pointing error
```

This is the angular error between the assumed nadir-facing body axis and the Earth/nadir direction. A smaller value means the satellite is closer to nadir pointing.

The second plot shows:

```text
Sun-pointing error during sunlight
```

This is the angular error between the assumed solar-array normal direction and the Sun direction. A smaller value means the solar array is more closely aligned with the Sun.

The third plot shows:

```text
Ground-station antenna pointing error
```

This is the angular error between the assumed antenna body axis and the direction from the satellite to the Zhongli ground station. A smaller value means the antenna is more closely aligned with the ground station.

### Results

The computed pointing statistics are:

```text
Median nadir pointing error = 43.84 deg
Median Sun pointing error = 89.97 deg
Median ground-station pointing error = 101.11 deg
```

Some time intervals show nadir pointing error close to `0 deg`, suggesting that the satellite may be close to Earth-pointing during those periods. However, the Sun-pointing and ground-station pointing errors are generally large under the current body-axis assumptions.

### Engineering Meaning

This figure is one of the most important extensions in the project. It turns raw quaternion telemetry into interpretable pointing-performance metrics.

The result depends strongly on the assumed spacecraft body axes:

```matlab
nadirBoresightBody = [0; 0; 1];
solarArrayNormalBody = [1; 0; 0];
groundStationAntennaBody = [0; 0; 1];
```

If spacecraft CAD data or official ADCS documentation becomes available, these body-axis assumptions should be calibrated for more accurate interpretation.

## Figure 4: Zhongli Ground-Station Geometry and Access Checks

![Zhongli ground-station geometry and access checks](outputs_enhanced/figures/04_access_timeline.png)

### Purpose

This figure evaluates whether the satellite is visible from the Zhongli ground station and whether the spacecraft attitude also allows sensor or antenna alignment.

### What the Figure Shows

The first plot shows:

```text
Elevation angle from Zhongli
```

When elevation is greater than `0 deg`, the satellite is above the local horizon and is geometrically visible from the ground station.

The second plot shows:

```text
Range from Zhongli
```

This is the distance between the satellite and the Zhongli ground station. Shorter range generally provides better communication geometry.

The third plot shows:

```text
Telemetry-time access candidates
```

It compares two conditions:

- `Elevation > 0`: the satellite is geometrically visible
- `Visible and sensor aligned`: the satellite is visible and the assumed sensor or antenna axis is aligned within the view-angle threshold

### Results

The access results are:

```text
Geometric access windows = 1
Sensor-limited access windows = 0
Link windows = 0
```

This means that the satellite has one geometric pass over the Zhongli ground station during the analyzed period. However, the sensor or antenna does not satisfy the `30 deg` pointing constraint during that pass, so no sensor-limited access or link window is detected.

### Engineering Meaning

This figure highlights an important mission-analysis concept:

```text
Geometric visibility does not guarantee mission availability.
```

For an actual communication or sensing opportunity, the following conditions must be considered together:

- The satellite must be above the ground-station horizon.
- The range and elevation geometry must be acceptable.
- The spacecraft attitude must align the sensor or antenna with the target.
- The communication or sensor link must satisfy its constraints.

Therefore, this figure upgrades a simple orbit-access analysis into a mission-availability analysis.

## Overall Summary

Together, the four figures form a complete ADCS and access-analysis workflow:

1. Validate quaternion telemetry quality.
2. Analyze body-rate stability.
3. Convert attitude telemetry into nadir, Sun, and ground-station pointing errors.
4. Combine ground-station geometry with attitude alignment to evaluate mission availability.

This enhancement turns the original satellite attitude animation into a quantitative and portfolio-ready engineering analysis tool.

